name: Build On Push
on:
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          make get-bins
          make test
          make gorelease-snapshot

     
